# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prideflow DocGen

on:
  push:
    branches:
      - master

jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Dependencies ğŸ“¦
        run: npm ci

      - name: Generate Docs âš™
        run: npm run docs

      - name: Deploy Docs ğŸš€
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/sebenns/Pride
          target_branch: master
          target_directory: docs
